# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo75_restaurante_pedidos.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RestaurantePedidos(object):
    def setupUi(self, RestaurantePedidos):
        RestaurantePedidos.setObjectName("RestaurantePedidos")
        RestaurantePedidos.resize(320, 240)
        RestaurantePedidos.setMinimumSize(QtCore.QSize(320, 240))
        RestaurantePedidos.setMaximumSize(QtCore.QSize(320, 240))
        self.verticalLayoutWidget = QtWidgets.QWidget(RestaurantePedidos)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(4, 4, 311, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ver_principal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ver_principal.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.twd_tabs = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.twd_tabs.setObjectName("twd_tabs")
        self.tab_productos = QtWidgets.QWidget()
        self.tab_productos.setObjectName("tab_productos")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_productos)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 1, 301, 201))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.lay_hor_productos = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.lay_hor_productos.setContentsMargins(0, 0, 0, 0)
        self.lay_hor_productos.setObjectName("lay_hor_productos")
        self.gbx_panaderia = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.gbx_panaderia.setObjectName("gbx_panaderia")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.gbx_panaderia)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(7, 19, 131, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.lay_ver_panaderia = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.lay_ver_panaderia.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_panaderia.setObjectName("lay_ver_panaderia")
        self.chk_tostada = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.chk_tostada.setObjectName("chk_tostada")
        self.lay_ver_panaderia.addWidget(self.chk_tostada)
        self.chk_galleta = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.chk_galleta.setObjectName("chk_galleta")
        self.lay_ver_panaderia.addWidget(self.chk_galleta)
        self.chk_croissan = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.chk_croissan.setObjectName("chk_croissan")
        self.lay_ver_panaderia.addWidget(self.chk_croissan)
        self.chk_sandwich = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.chk_sandwich.setObjectName("chk_sandwich")
        self.lay_ver_panaderia.addWidget(self.chk_sandwich)
        self.chk_pan_integral = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.chk_pan_integral.setObjectName("chk_pan_integral")
        self.lay_ver_panaderia.addWidget(self.chk_pan_integral)
        self.lay_hor_productos.addWidget(self.gbx_panaderia)
        self.gbx_bebidas = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.gbx_bebidas.setObjectName("gbx_bebidas")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.gbx_bebidas)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(6, 20, 131, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.lay_ver_bebidas = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.lay_ver_bebidas.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_bebidas.setObjectName("lay_ver_bebidas")
        self.chk_cafe = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.chk_cafe.setObjectName("chk_cafe")
        self.lay_ver_bebidas.addWidget(self.chk_cafe)
        self.chk_chocolate = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.chk_chocolate.setObjectName("chk_chocolate")
        self.lay_ver_bebidas.addWidget(self.chk_chocolate)
        self.chk_milo = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.chk_milo.setObjectName("chk_milo")
        self.lay_ver_bebidas.addWidget(self.chk_milo)
        self.chk_jugo_naranja = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.chk_jugo_naranja.setObjectName("chk_jugo_naranja")
        self.lay_ver_bebidas.addWidget(self.chk_jugo_naranja)
        self.chk_aromatica = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.chk_aromatica.setObjectName("chk_aromatica")
        self.lay_ver_bebidas.addWidget(self.chk_aromatica)
        self.lay_hor_productos.addWidget(self.gbx_bebidas)
        self.twd_tabs.addTab(self.tab_productos, "")
        self.tab_metodo_pago = QtWidgets.QWidget()
        self.tab_metodo_pago.setObjectName("tab_metodo_pago")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_metodo_pago)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 301, 151))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.lay_ver_metodos_pago = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.lay_ver_metodos_pago.setContentsMargins(10, 0, 0, 0)
        self.lay_ver_metodos_pago.setObjectName("lay_ver_metodos_pago")
        self.rbn_efectivo = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.rbn_efectivo.setObjectName("rbn_efectivo")
        self.lay_ver_metodos_pago.addWidget(self.rbn_efectivo)
        self.rbn_tarjeta_credito = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.rbn_tarjeta_credito.setObjectName("rbn_tarjeta_credito")
        self.lay_ver_metodos_pago.addWidget(self.rbn_tarjeta_credito)
        self.rbn_tarjeta_debito = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.rbn_tarjeta_debito.setObjectName("rbn_tarjeta_debito")
        self.lay_ver_metodos_pago.addWidget(self.rbn_tarjeta_debito)
        self.rbn_pago_electronico = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.rbn_pago_electronico.setObjectName("rbn_pago_electronico")
        self.lay_ver_metodos_pago.addWidget(self.rbn_pago_electronico)
        self.twd_tabs.addTab(self.tab_metodo_pago, "")
        self.tab_entrega = QtWidgets.QWidget()
        self.tab_entrega.setObjectName("tab_entrega")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_entrega)
        self.formLayoutWidget.setGeometry(QtCore.QRect(2, 2, 301, 163))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.lay_frm_entrega = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.lay_frm_entrega.setContentsMargins(10, 10, 10, 0)
        self.lay_frm_entrega.setObjectName("lay_frm_entrega")
        self.lbl_nombre_completo = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_nombre_completo.setObjectName("lbl_nombre_completo")
        self.lay_frm_entrega.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre_completo)
        self.txt_nombre_completo = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_nombre_completo.setObjectName("txt_nombre_completo")
        self.lay_frm_entrega.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_nombre_completo)
        self.lbl_direccion = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_direccion.setObjectName("lbl_direccion")
        self.lay_frm_entrega.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_direccion)
        self.txt_direccion = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_direccion.setObjectName("txt_direccion")
        self.lay_frm_entrega.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_direccion)
        self.lbl_observaciones = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_observaciones.setObjectName("lbl_observaciones")
        self.lay_frm_entrega.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_observaciones)
        self.txt_observaciones = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.txt_observaciones.setObjectName("txt_observaciones")
        self.lay_frm_entrega.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_observaciones)
        self.btn_enviar_solicitud = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_enviar_solicitud.setObjectName("btn_enviar_solicitud")
        self.lay_frm_entrega.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btn_enviar_solicitud)
        self.twd_tabs.addTab(self.tab_entrega, "")
        self.lay_ver_principal.addWidget(self.twd_tabs)

        self.retranslateUi(RestaurantePedidos)
        self.twd_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RestaurantePedidos)

    def retranslateUi(self, RestaurantePedidos):
        _translate = QtCore.QCoreApplication.translate
        RestaurantePedidos.setWindowTitle(_translate("RestaurantePedidos", "Restaurante - Pedidos"))
        self.gbx_panaderia.setTitle(_translate("RestaurantePedidos", "Panadería"))
        self.chk_tostada.setText(_translate("RestaurantePedidos", "Tostada"))
        self.chk_galleta.setText(_translate("RestaurantePedidos", "Galleta"))
        self.chk_croissan.setText(_translate("RestaurantePedidos", "Croissan"))
        self.chk_sandwich.setText(_translate("RestaurantePedidos", "Sandwich"))
        self.chk_pan_integral.setText(_translate("RestaurantePedidos", "Pan integral"))
        self.gbx_bebidas.setTitle(_translate("RestaurantePedidos", "Bebidas"))
        self.chk_cafe.setText(_translate("RestaurantePedidos", "Café"))
        self.chk_chocolate.setText(_translate("RestaurantePedidos", "Chocolate"))
        self.chk_milo.setText(_translate("RestaurantePedidos", "Milo"))
        self.chk_jugo_naranja.setText(_translate("RestaurantePedidos", "Jugo de naranja"))
        self.chk_aromatica.setText(_translate("RestaurantePedidos", "Aromática"))
        self.twd_tabs.setTabText(self.twd_tabs.indexOf(self.tab_productos), _translate("RestaurantePedidos", "Menú"))
        self.rbn_efectivo.setText(_translate("RestaurantePedidos", "Efectivo"))
        self.rbn_tarjeta_credito.setText(_translate("RestaurantePedidos", "Tarjeta crédito"))
        self.rbn_tarjeta_debito.setText(_translate("RestaurantePedidos", "Tarjeta débito"))
        self.rbn_pago_electronico.setText(_translate("RestaurantePedidos", "Pago electrónico (vía Web)"))
        self.twd_tabs.setTabText(self.twd_tabs.indexOf(self.tab_metodo_pago), _translate("RestaurantePedidos", "Método de pago"))
        self.lbl_nombre_completo.setText(_translate("RestaurantePedidos", "Nombre completo:"))
        self.lbl_direccion.setText(_translate("RestaurantePedidos", "Dirección:"))
        self.lbl_observaciones.setText(_translate("RestaurantePedidos", "Observaciones:"))
        self.btn_enviar_solicitud.setText(_translate("RestaurantePedidos", "Enviar solicitud de pedido"))
        self.twd_tabs.setTabText(self.twd_tabs.indexOf(self.tab_entrega), _translate("RestaurantePedidos", "Entrega"))
