# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo50_heladeria.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Heladeria(object):
    def setupUi(self, Heladeria):
        Heladeria.setObjectName("Heladeria")
        Heladeria.resize(480, 340)
        Heladeria.setMinimumSize(QtCore.QSize(480, 340))
        Heladeria.setMaximumSize(QtCore.QSize(480, 340))
        self.wdg_principal = QtWidgets.QWidget(Heladeria)
        self.wdg_principal.setObjectName("wdg_principal")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.wdg_principal)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ver_principal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ver_principal.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.lay_ver_principal.setContentsMargins(5, 0, 5, 0)
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.lbl_titulo = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_titulo.setFont(font)
        self.lbl_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lay_ver_principal.addWidget(self.lbl_titulo)
        self.lay_hor_etiquetas = QtWidgets.QHBoxLayout()
        self.lay_hor_etiquetas.setObjectName("lay_hor_etiquetas")
        self.lbl_seleccion_helado = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_seleccion_helado.setObjectName("lbl_seleccion_helado")
        self.lay_hor_etiquetas.addWidget(self.lbl_seleccion_helado)
        self.lbl_seleccion_bebida = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_seleccion_bebida.setObjectName("lbl_seleccion_bebida")
        self.lay_hor_etiquetas.addWidget(self.lbl_seleccion_bebida)
        self.lay_ver_principal.addLayout(self.lay_hor_etiquetas)
        self.lay_hor_opciones = QtWidgets.QHBoxLayout()
        self.lay_hor_opciones.setObjectName("lay_hor_opciones")
        self.gbx_helados = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.gbx_helados.setObjectName("gbx_helados")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.gbx_helados)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 221, 88))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.lay_ver_helados = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.lay_ver_helados.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_helados.setObjectName("lay_ver_helados")
        self.chk_chocolate = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.chk_chocolate.setObjectName("chk_chocolate")
        self.lay_ver_helados.addWidget(self.chk_chocolate)
        self.chk_vainilla = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.chk_vainilla.setObjectName("chk_vainilla")
        self.lay_ver_helados.addWidget(self.chk_vainilla)
        self.chk_arequipe = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.chk_arequipe.setObjectName("chk_arequipe")
        self.lay_ver_helados.addWidget(self.chk_arequipe)
        self.chk_ron_pasas = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.chk_ron_pasas.setObjectName("chk_ron_pasas")
        self.lay_ver_helados.addWidget(self.chk_ron_pasas)
        self.lay_hor_opciones.addWidget(self.gbx_helados)
        self.gbx_bebidas = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.gbx_bebidas.setObjectName("gbx_bebidas")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.gbx_bebidas)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 221, 65))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.lay_ver_bebidas = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.lay_ver_bebidas.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_bebidas.setObjectName("lay_ver_bebidas")
        self.chk_cafe = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.chk_cafe.setObjectName("chk_cafe")
        self.lay_ver_bebidas.addWidget(self.chk_cafe)
        self.chk_agua = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.chk_agua.setObjectName("chk_agua")
        self.lay_ver_bebidas.addWidget(self.chk_agua)
        self.chk_soda = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.chk_soda.setObjectName("chk_soda")
        self.lay_ver_bebidas.addWidget(self.chk_soda)
        self.lay_hor_opciones.addWidget(self.gbx_bebidas)
        self.lay_ver_principal.addLayout(self.lay_hor_opciones)
        self.lbl_total = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_total.setObjectName("lbl_total")
        self.lay_ver_principal.addWidget(self.lbl_total)
        self.lay_ver_principal.setStretch(0, 1)
        self.lay_ver_principal.setStretch(1, 1)
        self.lay_ver_principal.setStretch(2, 2)
        self.lay_ver_principal.setStretch(3, 1)
        Heladeria.setCentralWidget(self.wdg_principal)
        self.mbr_principal = QtWidgets.QMenuBar(Heladeria)
        self.mbr_principal.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.mbr_principal.setObjectName("mbr_principal")
        Heladeria.setMenuBar(self.mbr_principal)
        self.stt_principal = QtWidgets.QStatusBar(Heladeria)
        self.stt_principal.setObjectName("stt_principal")
        Heladeria.setStatusBar(self.stt_principal)

        self.retranslateUi(Heladeria)
        QtCore.QMetaObject.connectSlotsByName(Heladeria)

    def retranslateUi(self, Heladeria):
        _translate = QtCore.QCoreApplication.translate
        Heladeria.setWindowTitle(_translate("Heladeria", "Heladería"))
        self.lbl_titulo.setText(_translate("Heladeria", "Menú"))
        self.lbl_seleccion_helado.setText(_translate("Heladeria", "Seleccione su helado:"))
        self.lbl_seleccion_bebida.setText(_translate("Heladeria", "Seleccione su bebida:"))
        self.gbx_helados.setTitle(_translate("Heladeria", "Helados"))
        self.chk_chocolate.setText(_translate("Heladeria", "Chocolate $3"))
        self.chk_vainilla.setText(_translate("Heladeria", "Vainilla $2"))
        self.chk_arequipe.setText(_translate("Heladeria", "Arequipe $3"))
        self.chk_ron_pasas.setText(_translate("Heladeria", "Ron con pasas $4"))
        self.gbx_bebidas.setTitle(_translate("Heladeria", "Bebidas"))
        self.chk_cafe.setText(_translate("Heladeria", "Café $2"))
        self.chk_agua.setText(_translate("Heladeria", "Agua $1"))
        self.chk_soda.setText(_translate("Heladeria", "Soda $3"))
        self.lbl_total.setText(_translate("Heladeria", "Total: $0"))
