# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo67_tabla_lenguajes.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TablaLenguajes(object):
    def setupUi(self, TablaLenguajes):
        TablaLenguajes.setObjectName("TablaLenguajes")
        TablaLenguajes.resize(338, 240)
        self.verticalLayoutWidget = QtWidgets.QWidget(TablaLenguajes)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(7, 3, 320, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ver_principal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ver_principal.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.tbl_lenguajes = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tbl_lenguajes.setObjectName("tbl_lenguajes")
        self.tbl_lenguajes.setColumnCount(3)
        self.tbl_lenguajes.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_lenguajes.setItem(5, 2, item)
        self.lay_ver_principal.addWidget(self.tbl_lenguajes)

        self.retranslateUi(TablaLenguajes)
        QtCore.QMetaObject.connectSlotsByName(TablaLenguajes)

    def retranslateUi(self, TablaLenguajes):
        _translate = QtCore.QCoreApplication.translate
        TablaLenguajes.setWindowTitle(_translate("TablaLenguajes", "Lenguajes"))
        item = self.tbl_lenguajes.verticalHeaderItem(1)
        item.setText(_translate("TablaLenguajes", "1"))
        item = self.tbl_lenguajes.verticalHeaderItem(2)
        item.setText(_translate("TablaLenguajes", "2"))
        item = self.tbl_lenguajes.verticalHeaderItem(3)
        item.setText(_translate("TablaLenguajes", "3"))
        item = self.tbl_lenguajes.verticalHeaderItem(4)
        item.setText(_translate("TablaLenguajes", "4"))
        item = self.tbl_lenguajes.verticalHeaderItem(5)
        item.setText(_translate("TablaLenguajes", "5"))
        item = self.tbl_lenguajes.horizontalHeaderItem(0)
        item.setText(_translate("TablaLenguajes", "ID"))
        item = self.tbl_lenguajes.horizontalHeaderItem(1)
        item.setText(_translate("TablaLenguajes", "Nombre"))
        item = self.tbl_lenguajes.horizontalHeaderItem(2)
        item.setText(_translate("TablaLenguajes", "Versión"))
        __sortingEnabled = self.tbl_lenguajes.isSortingEnabled()
        self.tbl_lenguajes.setSortingEnabled(False)
        item = self.tbl_lenguajes.item(1, 0)
        item.setText(_translate("TablaLenguajes", "1001"))
        item = self.tbl_lenguajes.item(1, 1)
        item.setText(_translate("TablaLenguajes", "Python"))
        item = self.tbl_lenguajes.item(1, 2)
        item.setText(_translate("TablaLenguajes", "3.8.0"))
        item = self.tbl_lenguajes.item(2, 0)
        item.setText(_translate("TablaLenguajes", "1002"))
        item = self.tbl_lenguajes.item(2, 1)
        item.setText(_translate("TablaLenguajes", "JavaScript"))
        item = self.tbl_lenguajes.item(2, 2)
        item.setText(_translate("TablaLenguajes", "ES6"))
        item = self.tbl_lenguajes.item(3, 0)
        item.setText(_translate("TablaLenguajes", "1003"))
        item = self.tbl_lenguajes.item(3, 1)
        item.setText(_translate("TablaLenguajes", "Java"))
        item = self.tbl_lenguajes.item(3, 2)
        item.setText(_translate("TablaLenguajes", "14"))
        item = self.tbl_lenguajes.item(4, 0)
        item.setText(_translate("TablaLenguajes", "1004"))
        item = self.tbl_lenguajes.item(4, 1)
        item.setText(_translate("TablaLenguajes", "PHP"))
        item = self.tbl_lenguajes.item(4, 2)
        item.setText(_translate("TablaLenguajes", "7.1.2"))
        item = self.tbl_lenguajes.item(5, 0)
        item.setText(_translate("TablaLenguajes", "1005"))
        item = self.tbl_lenguajes.item(5, 1)
        item.setText(_translate("TablaLenguajes", "C#"))
        item = self.tbl_lenguajes.item(5, 2)
        item.setText(_translate("TablaLenguajes", "7"))
        self.tbl_lenguajes.setSortingEnabled(__sortingEnabled)
