# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ex2_gestor_inventario.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GestorInventario(object):
    def setupUi(self, GestorInventario):
        GestorInventario.setObjectName("GestorInventario")
        GestorInventario.resize(640, 480)
        self.wdg_principal = QtWidgets.QWidget(GestorInventario)
        self.wdg_principal.setObjectName("wdg_principal")
        self.gridLayout = QtWidgets.QGridLayout(self.wdg_principal)
        self.gridLayout.setObjectName("gridLayout")
        self.lay_ver_principal = QtWidgets.QVBoxLayout()
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.mdi_principal = QtWidgets.QMdiArea(self.wdg_principal)
        self.mdi_principal.setObjectName("mdi_principal")
        self.lay_ver_principal.addWidget(self.mdi_principal)
        self.gridLayout.addLayout(self.lay_ver_principal, 0, 0, 1, 1)
        GestorInventario.setCentralWidget(self.wdg_principal)
        self.mbr_principal = QtWidgets.QMenuBar(GestorInventario)
        self.mbr_principal.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.mbr_principal.setObjectName("mbr_principal")
        self.mnu_archivo = QtWidgets.QMenu(self.mbr_principal)
        self.mnu_archivo.setObjectName("mnu_archivo")
        self.mnu_productos = QtWidgets.QMenu(self.mbr_principal)
        self.mnu_productos.setObjectName("mnu_productos")
        self.mnu_reportes = QtWidgets.QMenu(self.mbr_principal)
        self.mnu_reportes.setObjectName("mnu_reportes")
        self.mnu_ayuda = QtWidgets.QMenu(self.mbr_principal)
        self.mnu_ayuda.setObjectName("mnu_ayuda")
        GestorInventario.setMenuBar(self.mbr_principal)
        self.stt_principal = QtWidgets.QStatusBar(GestorInventario)
        self.stt_principal.setObjectName("stt_principal")
        GestorInventario.setStatusBar(self.stt_principal)
        self.mni_salir = QtWidgets.QAction(GestorInventario)
        self.mni_salir.setObjectName("mni_salir")
        self.mni_producto_registrar = QtWidgets.QAction(GestorInventario)
        self.mni_producto_registrar.setObjectName("mni_producto_registrar")
        self.mni_producto_vender = QtWidgets.QAction(GestorInventario)
        self.mni_producto_vender.setObjectName("mni_producto_vender")
        self.mni_producto_buscar = QtWidgets.QAction(GestorInventario)
        self.mni_producto_buscar.setObjectName("mni_producto_buscar")
        self.mni_producto_cambiar_disponibilidad = QtWidgets.QAction(GestorInventario)
        self.mni_producto_cambiar_disponibilidad.setObjectName("mni_producto_cambiar_disponibilidad")
        self.mni_reporte_rango_fechas = QtWidgets.QAction(GestorInventario)
        self.mni_reporte_rango_fechas.setObjectName("mni_reporte_rango_fechas")
        self.mni_reporte_productos_mas_vendidos = QtWidgets.QAction(GestorInventario)
        self.mni_reporte_productos_mas_vendidos.setObjectName("mni_reporte_productos_mas_vendidos")
        self.mni_reporte_productos_menos_vendidos = QtWidgets.QAction(GestorInventario)
        self.mni_reporte_productos_menos_vendidos.setObjectName("mni_reporte_productos_menos_vendidos")
        self.mni_acerca_de = QtWidgets.QAction(GestorInventario)
        self.mni_acerca_de.setObjectName("mni_acerca_de")
        self.mnu_archivo.addAction(self.mni_salir)
        self.mnu_productos.addAction(self.mni_producto_registrar)
        self.mnu_productos.addAction(self.mni_producto_vender)
        self.mnu_productos.addAction(self.mni_producto_buscar)
        self.mnu_productos.addAction(self.mni_producto_cambiar_disponibilidad)
        self.mnu_reportes.addAction(self.mni_reporte_rango_fechas)
        self.mnu_reportes.addAction(self.mni_reporte_productos_mas_vendidos)
        self.mnu_reportes.addAction(self.mni_reporte_productos_menos_vendidos)
        self.mnu_ayuda.addAction(self.mni_acerca_de)
        self.mbr_principal.addAction(self.mnu_archivo.menuAction())
        self.mbr_principal.addAction(self.mnu_productos.menuAction())
        self.mbr_principal.addAction(self.mnu_reportes.menuAction())
        self.mbr_principal.addAction(self.mnu_ayuda.menuAction())

        self.retranslateUi(GestorInventario)
        QtCore.QMetaObject.connectSlotsByName(GestorInventario)

    def retranslateUi(self, GestorInventario):
        _translate = QtCore.QCoreApplication.translate
        GestorInventario.setWindowTitle(_translate("GestorInventario", "Gestor Inventario - Dispositivos S.a.s."))
        self.mnu_archivo.setTitle(_translate("GestorInventario", "Archivo"))
        self.mnu_productos.setTitle(_translate("GestorInventario", "Productos"))
        self.mnu_reportes.setTitle(_translate("GestorInventario", "Reportes"))
        self.mnu_ayuda.setTitle(_translate("GestorInventario", "Ayuda"))
        self.mni_salir.setText(_translate("GestorInventario", "Salir"))
        self.mni_salir.setShortcut(_translate("GestorInventario", "Ctrl+Q"))
        self.mni_producto_registrar.setText(_translate("GestorInventario", "Registrar"))
        self.mni_producto_registrar.setShortcut(_translate("GestorInventario", "Ctrl+R"))
        self.mni_producto_vender.setText(_translate("GestorInventario", "Vender"))
        self.mni_producto_vender.setShortcut(_translate("GestorInventario", "Ctrl+E"))
        self.mni_producto_buscar.setText(_translate("GestorInventario", "Buscar"))
        self.mni_producto_buscar.setShortcut(_translate("GestorInventario", "Ctrl+B"))
        self.mni_producto_cambiar_disponibilidad.setText(_translate("GestorInventario", "Cambiar disponibilidad"))
        self.mni_producto_cambiar_disponibilidad.setShortcut(_translate("GestorInventario", "Ctrl+D"))
        self.mni_reporte_rango_fechas.setText(_translate("GestorInventario", "Ventas en un rango de fechas"))
        self.mni_reporte_rango_fechas.setShortcut(_translate("GestorInventario", "Ctrl+F"))
        self.mni_reporte_productos_mas_vendidos.setText(_translate("GestorInventario", "Top 5 productos más vendidos"))
        self.mni_reporte_productos_mas_vendidos.setShortcut(_translate("GestorInventario", "Ctrl+J"))
        self.mni_reporte_productos_menos_vendidos.setText(_translate("GestorInventario", "Top 5 productos menos vendidos"))
        self.mni_reporte_productos_menos_vendidos.setShortcut(_translate("GestorInventario", "Ctrl+K"))
        self.mni_acerca_de.setText(_translate("GestorInventario", "Acerca de..."))
